import G6 from "@antv/g6";
const data = {

    'nodes':
    [
       {
          'id':'0',
          'label':'bizframe-cloud-server-2.0.85.2.jar: activation-1.1.jar'
       },
       {
          'comboId':'com.rabbitmq',
          'id':'1',
          'label':'bizframe-cloud-server-2.0.85.2.jar: amqp-client-5.7.3.jar'
       },
       {
          'comboId':'org.codehaus.mojo',
          'id':'2',
          'label':'bizframe-cloud-server-2.0.85.2.jar: animal-sniffer-annotations-1.14.jar'
       },
       {
          'comboId':'org.apache.skywalking',
          'id':'3',
          'label':'bizframe-cloud-server-2.0.85.2.jar: apm-toolkit-opentracing-8.1.0.jar'
       },
       {
          'comboId':'org.apache.skywalking',
          'id':'4',
          'label':'bizframe-cloud-server-2.0.85.2.jar: apm-toolkit-trace-8.1.0.jar'
       },
       {
          'comboId':'org.apache.skywalking',
          'id':'5',
          'label':'bizframe-cloud-server-2.0.85.2.jar: aspectjweaver-1.9.5.jar'
       },
       {
          'comboId':'org.apache.yetus',
          'id':'6',
          'label':'bizframe-cloud-server-2.0.85.2.jar: audience-annotations-0.5.0.jar'
       },
       {
          'comboId':'org.apache.yetus',
          'id':'7',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bcprov-jdk15on-1.68.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'8',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-api-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'9',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-api-bank-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'10',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-cloud-api-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'11',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-cloud-bank-api-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'12',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-cloud-bank-impl-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'13',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-cloud-impl-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'14',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-common-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'15',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-core-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'16',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-rabbitmq-client-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'17',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-rabbitmq-server-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'18',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-resources-2.0.85.2-nolib.war'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'19',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-sql-common-2.0.85.2-nolib.war'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'20',
          'label':'bizframe-cloud-server-2.0.85.2.jar: bizframe-xml-impl-2.0.85.2.jar'
       },
       {
          'comboId':'com.hundsun.jres.bizframe2',
          'id':'21',
          'label':'bizframe-cloud-server-2.0.85.2.jar: checker-compat-qual-2.0.0.jar'
       },
       {
          'comboId':'com.fasterxml',
          'id':'22',
          'label':'bizframe-cloud-server-2.0.85.2.jar: classmate-1.5.1.jar'
       },
       {
          'comboId':'com.hundsun.jres.common',
          'id':'23',
          'label':'bizframe-cloud-server-2.0.85.2.jar: common.xml-1.0.3.jar'
       },
       {
          'comboId':'commons-beanutils',
          'id':'24',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-beanutils-1.9.4.jar'
       },
       {
          'comboId':'commons-codec',
          'id':'25',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-codec-1.13.jar'
       },
       {
          'comboId':'commons-collections',
          'id':'26',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-collections-3.2.2.jar'
       },
       {
          'comboId':'org.apache.commons',
          'id':'27',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-collections4-4.4.jar'
       },
       {
          'comboId':'org.apache.commons',
          'id':'28',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-compress-1.19.jar'
       },
       {
          'comboId':'commons-fileupload',
          'id':'29',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-fileupload-1.3.3.jar'
       },
       {
          'comboId':'commons-io',
          'id':'30',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-io-2.6.jar'
       },
       {
          'comboId':'commons-lang',
          'id':'31',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-lang-2.6.jar'
       },
       {
          'comboId':'org.apache.commons',
          'id':'32',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-lang3-3.8.1.jar'
       },
       {
          'comboId':'commons-logging',
          'id':'33',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-logging-1.2.jar'
       },
       {
          'comboId':'org.apache.commons',
          'id':'34',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-math3-3.6.1.jar'
       },
       {
          'comboId':'org.apache.commons',
          'id':'35',
          'label':'bizframe-cloud-server-2.0.85.2.jar: commons-pool2-2.7.0.jar'
       },
       {
          'comboId':'io.opentracing',
          'id':'36',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar'
       },
       {
          'comboId':'com.google.guava',
          'id':'37',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curator-client-4.2.0.jar'
       },
       {
          'comboId':'org.apache.curator',
          'id':'38',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curator-framework-4.2.0.jar'
       },
       {
          'comboId':'org.apache.curator',
          'id':'39',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curator-recipes-4.2.0.jar'
       },
       {
          'comboId':'com.github.virtuald',
          'id':'40',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curvesapi-1.06.jar'
       },
       {
          'comboId':'com.github.virtuald',
          'id':'41',
          'label':'bizframe-cloud-server-2.0.85.2.jar: disruptor-3.4.2.jar'
       },
       {
          'comboId':'com.github.virtuald',
          'id':'42',
          'label':'bizframe-cloud-server-2.0.85.2.jar: dom4j-2.1.3.jar'
       },
       {
          'comboId':'com.alibaba',
          'id':'43',
          'label':'bizframe-cloud-server-2.0.85.2.jar: druid-1.1.21.jar'
       },
       {
          'comboId':'com.alibaba',
          'id':'44',
          'label':'bizframe-cloud-server-2.0.85.2.jar: druid-spring-boot-starter-1.2.8.jar'
       },
       {
          'comboId':'org.terracotta',
          'id':'45',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ehcache-3.3.1.jar'
       },
       {
          'comboId':'org.owasp.encoder',
          'id':'46',
          'label':'bizframe-cloud-server-2.0.85.2.jar: encoder-1.2.2.jar'
       },
       {
          'comboId':'com.google.errorprone',
          'id':'47',
          'label':'bizframe-cloud-server-2.0.85.2.jar: error_prone_annotations-2.3.4.jar'
       },
       {
          'comboId':'net.sf.ezmorph',
          'id':'48',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ezmorph-1.0.6.jar'
       },
       {
          'comboId':'com.alibaba',
          'id':'49',
          'label':'bizframe-cloud-server-2.0.85.2.jar: fastjson-1.2.76.jar'
       },
       {
          'comboId':'com.google.code.gson',
          'id':'50',
          'label':'bizframe-cloud-server-2.0.85.2.jar: gson-2.8.9.jar'
       },
       {
          'comboId':'com.google.guava',
          'id':'51',
          'label':'bizframe-cloud-server-2.0.85.2.jar: guava-25.0-jre.jar'
       },
       {
          'comboId':'org.hdrhistogram',
          'id':'52',
          'label':'bizframe-cloud-server-2.0.85.2.jar: HdrHistogram-2.1.11.jar'
       },
       {
          'comboId':'org.hibernate.validator',
          'id':'53',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hibernate-validator-6.0.18.Final.jar'
       },
       {
          'comboId':'com.zaxxer',
          'id':'54',
          'label':'bizframe-cloud-server-2.0.85.2.jar: HikariCP-3.4.1.jar'
       },
       {
          'comboId':'org.apache.httpcomponents',
          'id':'55',
          'label':'bizframe-cloud-server-2.0.85.2.jar: httpclient-4.5.10.jar'
       },
       {
          'comboId':'org.apache.httpcomponents',
          'id':'56',
          'label':'bizframe-cloud-server-2.0.85.2.jar: httpcore-4.4.12.jar'
       },
       {
          'comboId':'cn.hutool',
          'id':'57',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar'
       },
       {
          'comboId':'com.google.j2objc',
          'id':'58',
          'label':'bizframe-cloud-server-2.0.85.2.jar: j2objc-annotations-1.1.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.core',
          'id':'59',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-annotations-2.11.3.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.core',
          'id':'60',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-core-2.11.3.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.core',
          'id':'61',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-databind-2.11.3.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.datatype',
          'id':'62',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-datatype-jdk8-2.11.3.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.datatype',
          'id':'63',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-datatype-jsr310-2.11.3.jar'
       },
       {
          'comboId':'com.fasterxml.jackson.module',
          'id':'64',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jackson-module-parameter-names-2.11.3.jar'
       },
       {
          'comboId':'jakarta.annotation',
          'id':'65',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jakarta.annotation-api-1.3.5.jar'
       },
       {
          'comboId':'jakarta.validation',
          'id':'66',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jakarta.validation-api-2.0.1.jar'
       },
       {
          'comboId':'com.couchbase.client',
          'id':'67',
          'label':'bizframe-cloud-server-2.0.85.2.jar: java-client-2.3.6.jar'
       },
       {
          'comboId':'com.couchbase.client',
          'id':'68',
          'label':'bizframe-cloud-server-2.0.85.2.jar: java-jwt-3.12.0.jar'
       },
       {
          'comboId':'org.javassist',
          'id':'69',
          'label':'bizframe-cloud-server-2.0.85.2.jar: javassist-3.20.0-GA.jar'
       },
       {
          'comboId':'javax.servlet',
          'id':'70',
          'label':'bizframe-cloud-server-2.0.85.2.jar: javax.servlet-api-4.0.0.jar'
       },
       {
          'comboId':'javax.servlet.jsp',
          'id':'71',
          'label':'bizframe-cloud-server-2.0.85.2.jar: javax.servlet.jsp-api-2.3.1.jar'
       },
       {
          'comboId':'org.jboss.logging',
          'id':'72',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jboss-logging-3.4.1.Final.jar'
       },
       {
          'comboId':'org.slf4j',
          'id':'73',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jcl-over-slf4j-1.7.29.jar'
       },
       {
          'comboId':'redis.clients',
          'id':'74',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jedis-3.1.0.jar'
       },
       {
          'comboId':'jline',
          'id':'75',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jline-0.9.94.jar'
       },
       {
          'comboId':'jline',
          'id':'76',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jna-5.0.0.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'77',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-api-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'78',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-core-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'79',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-couchbase-3.0.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'80',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-jedis-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'81',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-local-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'82',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-monitor-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'83',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-cache-redis-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'84',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'85',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-base-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'86',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-encrypt-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'87',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-extension-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'88',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-gm-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'89',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-partition-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'90',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-common-t2-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'91',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-db-api-3.0.8.5.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'92',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-db-core-3.0.8.5.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'93',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-db-def-3.0.8.5.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'94',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-db-monitor-3.0.8.5.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'95',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-monitor-api-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'96',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-monitor-common-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'97',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-adapter-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'98',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-amqp-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'99',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-amqp-configuration-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'100',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-api-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'101',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-api-compatible-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'102',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-core-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'103',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-db-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'104',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-monitor-common-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'105',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-monitor-springboot1-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'106',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-monitor-springboot2-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'107',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mq-monitor-starter-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'108',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mvc-jwt-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'109',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-mvc-registry-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'110',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-prometheus-monitor-api-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'111',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-api-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'112',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-def-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'113',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-def-log4j2-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'114',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-def-monitor-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'115',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-def-rule-monitor-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'116',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-springmvc-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'117',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-rpc-t2-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'118',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'119',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-cache-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'120',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-logkafka-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'121',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-mq-amqp-4.1.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'122',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-mvc-registry-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'123',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-mybatis-3.0.8.5.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'124',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-rpc-def-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'125',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-starter-rpc-mvc-registry-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'126',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-trace-api-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'127',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-trace-common-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'128',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-trace-core-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'129',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-trace-json-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'130',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jrescloud-trace-protobuff-3.0.16.4.jar'
       },
       {
          'comboId':'com.hundsun.jresplus',
          'id':'131',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jresplus-security-api-1.2.3.jar'
       },
       {
          'comboId':'com.hundsun.jresplus',
          'id':'132',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jresplus-security-core-1.2.3.jar'
       },
       {
          'comboId':'com.hundsun.jresplus',
          'id':'133',
          'label':'bizframe-cloud-server-2.0.85.2.jar: json-lib-2.4-jdk15.jar'
       },
       {
          'comboId':'org.jsoup',
          'id':'134',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jsoup-1.14.2.jar'
       },
       {
          'comboId':'com.github.jsqlparser',
          'id':'135',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jsqlparser-1.0.jar'
       },
       {
          'comboId':'com.google.code.findbugs',
          'id':'136',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jsr305-3.0.2.jar'
       },
       {
          'comboId':'com.google.code.findbugs',
          'id':'137',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jstl-1.2.jar'
       },
       {
          'comboId':'org.slf4j',
          'id':'138',
          'label':'bizframe-cloud-server-2.0.85.2.jar: jul-to-slf4j-1.7.29.jar'
       },
       {
          'comboId':'org.slf4j',
          'id':'139',
          'label':'bizframe-cloud-server-2.0.85.2.jar: kafka-clients-2.2.2.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'140',
          'label':'bizframe-cloud-server-2.0.85.2.jar: kryo-5.0.0-RC1.jar'
       },
       {
          'comboId':'org.latencyutils',
          'id':'141',
          'label':'bizframe-cloud-server-2.0.85.2.jar: LatencyUtils-2.0.3.jar'
       },
       {
          'comboId':'org.apache.logging.log4j',
          'id':'142',
          'label':'bizframe-cloud-server-2.0.85.2.jar: log4j-api-2.17.0.jar'
       },
       {
          'comboId':'org.apache.logging.log4j',
          'id':'143',
          'label':'bizframe-cloud-server-2.0.85.2.jar: log4j-core-2.17.0.jar'
       },
       {
          'comboId':'org.apache.logging.log4j',
          'id':'144',
          'label':'bizframe-cloud-server-2.0.85.2.jar: log4j-jul-2.17.0.jar'
       },
       {
          'comboId':'org.apache.logging.log4j',
          'id':'145',
          'label':'bizframe-cloud-server-2.0.85.2.jar: log4j-slf4j-impl-2.17.0.jar'
       },
       {
          'comboId':'org.apache.logging.log4j',
          'id':'146',
          'label':'bizframe-cloud-server-2.0.85.2.jar: lz4-java-1.5.0.jar'
       },
       {
          'comboId':'javax.mail',
          'id':'147',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mail-1.4.7.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'148',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'149',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-base-1.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'150',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-core-1.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'151',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-extra-1.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'152',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-spring-1.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'153',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-spring-boot-autoconfigure-2.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'154',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-spring-boot-starter-2.1.5.jar'
       },
       {
          'comboId':'tk.mybatis',
          'id':'155',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-weekend-1.1.5.jar'
       },
       {
          'comboId':'org.pcollections',
          'id':'156',
          'label':'bizframe-cloud-server-2.0.85.2.jar: micrometer-core-1.3.1.jar'
       },
       {
          'comboId':'org.pcollections',
          'id':'157',
          'label':'bizframe-cloud-server-2.0.85.2.jar: micrometer-registry-prometheus-1.3.1.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud.middleware',
          'id':'158',
          'label':'bizframe-cloud-server-2.0.85.2.jar: middleware-base-common-2.0.6.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud.middleware',
          'id':'159',
          'label':'bizframe-cloud-server-2.0.85.2.jar: middleware-base-exception-2.0.6.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud.middleware',
          'id':'160',
          'label':'bizframe-cloud-server-2.0.85.2.jar: middleware-tenant-api-1.0.0.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud.middleware',
          'id':'161',
          'label':'bizframe-cloud-server-2.0.85.2.jar: middleware-tenant-sdk-1.0.0.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'162',
          'label':'bizframe-cloud-server-2.0.85.2.jar: minlog-1.3.0.jar'
       },
       {
          'comboId':'io.github.x-stream',
          'id':'163',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mxparser-1.2.2.jar'
       },
       {
          'comboId':'org.javassist',
          'id':'164',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-3.5.6.jar'
       },
       {
          'comboId':'org.mybatis',
          'id':'165',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-spring-1.3.0.jar'
       },
       {
          'comboId':'org.mybatis.spring.boot',
          'id':'166',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-spring-boot-autoconfigure-2.2.0.jar'
       },
       {
          'comboId':'org.mybatis.spring.boot',
          'id':'167',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-spring-boot-starter-2.2.0.jar'
       },
       {
          'comboId':'org.mybatis.spring.boot',
          'id':'168',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mysql-connector-java-8.0.20.jar'
       },
       {
          'comboId':'com.alibaba.nacos',
          'id':'169',
          'label':'bizframe-cloud-server-2.0.85.2.jar: nacos-api-1.1.4.jar'
       },
       {
          'comboId':'com.alibaba.nacos',
          'id':'170',
          'label':'bizframe-cloud-server-2.0.85.2.jar: nacos-client-1.1.4.jar'
       },
       {
          'comboId':'com.alibaba.nacos',
          'id':'171',
          'label':'bizframe-cloud-server-2.0.85.2.jar: nacos-common-1.1.4.jar'
       },
       {
          'comboId':'io.netty',
          'id':'172',
          'label':'bizframe-cloud-server-2.0.85.2.jar: netty-3.10.6.Final.jar'
       },
       {
          'comboId':'io.netty',
          'id':'173',
          'label':'bizframe-cloud-server-2.0.85.2.jar: objenesis-2.6.jar'
       },
       {
          'comboId':'com.google.guava',
          'id':'174',
          'label':'bizframe-cloud-server-2.0.85.2.jar: oceanbase-client-1.1.7.jar'
       },
       {
          'comboId':'com.google.guava',
          'id':'175',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ojdbc8-12.2.0.1.0.jar'
       },
       {
          'comboId':'io.opentracing',
          'id':'176',
          'label':'bizframe-cloud-server-2.0.85.2.jar: opentracing-api-0.31.0.jar'
       },
       {
          'comboId':'io.opentracing',
          'id':'177',
          'label':'bizframe-cloud-server-2.0.85.2.jar: opentracing-noop-0.31.0.jar'
       },
       {
          'comboId':'io.opentracing',
          'id':'178',
          'label':'bizframe-cloud-server-2.0.85.2.jar: orai18n-12.1.0.2.0.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'179',
          'label':'bizframe-cloud-server-2.0.85.2.jar: pagehelper-5.1.4.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'180',
          'label':'bizframe-cloud-server-2.0.85.2.jar: pagehelper-spring-boot-autoconfigure-1.4.0.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'181',
          'label':'bizframe-cloud-server-2.0.85.2.jar: pagehelper-spring-boot-starter-1.4.0.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'182',
          'label':'bizframe-cloud-server-2.0.85.2.jar: persistence-api-1.0.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'183',
          'label':'bizframe-cloud-server-2.0.85.2.jar: poi-4.1.1.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'184',
          'label':'bizframe-cloud-server-2.0.85.2.jar: poi-ooxml-4.1.1.jar'
       },
       {
          'comboId':'com.github.pagehelper',
          'id':'185',
          'label':'bizframe-cloud-server-2.0.85.2.jar: poi-ooxml-schemas-4.1.1.jar'
       },
       {
          'comboId':'com.google.protobuf',
          'id':'186',
          'label':'bizframe-cloud-server-2.0.85.2.jar: protobuf-java-3.11.4.jar'
       },
       {
          'comboId':'com.google.protobuf',
          'id':'187',
          'label':'bizframe-cloud-server-2.0.85.2.jar: protobuf-java-util-3.11.4.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'188',
          'label':'bizframe-cloud-server-2.0.85.2.jar: reflectasm-1.11.7.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'189',
          'label':'bizframe-cloud-server-2.0.85.2.jar: rocksdbjni-5.18.3.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'190',
          'label':'bizframe-cloud-server-2.0.85.2.jar: rxjava-1.3.8.jar'
       },
       {
          'comboId':'com.esotericsoftware',
          'id':'191',
          'label':'bizframe-cloud-server-2.0.85.2.jar: servlet-api-2.5.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'192',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-cache-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'193',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-config-core-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'194',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-config-ogdl-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'195',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-core-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'196',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-crypto-cipher-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'197',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-crypto-core-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'198',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-crypto-hash-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'199',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-event-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'200',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-lang-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'201',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-spring-1.8.0.jar'
       },
       {
          'comboId':'org.apache.shiro',
          'id':'202',
          'label':'bizframe-cloud-server-2.0.85.2.jar: shiro-web-1.8.0.jar'
       },
       {
          'comboId':'io.prometheus',
          'id':'203',
          'label':'bizframe-cloud-server-2.0.85.2.jar: simpleclient-0.7.0.jar'
       },
       {
          'comboId':'io.prometheus',
          'id':'204',
          'label':'bizframe-cloud-server-2.0.85.2.jar: simpleclient_common-0.7.0.jar'
       },
       {
          'comboId':'org.slf4j',
          'id':'205',
          'label':'bizframe-cloud-server-2.0.85.2.jar: slf4j-api-1.7.29.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'206',
          'label':'bizframe-cloud-server-2.0.85.2.jar: snakeyaml-1.26.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'207',
          'label':'bizframe-cloud-server-2.0.85.2.jar: snappy-java-1.1.7.2.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'208',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spotbugs-annotations-3.1.9.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'209',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-aop-5.2.15.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'210',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-aspects-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'211',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-beans-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'212',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'213',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-actuator-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'214',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-actuator-autoconfigure-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.yaml',
          'id':'215',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-autoconfigure-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'216',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-legacy-2.1.0.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'217',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'218',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-actuator-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'219',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-aop-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'220',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-jdbc-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'221',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-json-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'222',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-log4j2-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'223',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-tomcat-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'224',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-validation-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'225',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-boot-starter-web-2.2.2.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'226',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-context-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'227',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-context-support-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.boot',
          'id':'228',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-core-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'229',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-data-commons-2.2.3.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'230',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-data-keyvalue-2.2.3.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'231',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-data-redis-2.2.3.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'232',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-expression-5.2.15.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'233',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-jcl-5.2.15.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'234',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-jdbc-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'235',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-orm-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'236',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-oxm-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'237',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-tx-5.2.15.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'238',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-web-5.2.15.RELEASE.jar'
       },
       {
          'comboId':'org.springframework.data',
          'id':'239',
          'label':'bizframe-cloud-server-2.0.85.2.jar: spring-webmvc-5.2.9.RELEASE.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'240',
          'label':'bizframe-cloud-server-2.0.85.2.jar: store-3.0.8.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'241',
          'label':'bizframe-cloud-server-2.0.85.2.jar: tomcat-embed-core-9.0.54.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'242',
          'label':'bizframe-cloud-server-2.0.85.2.jar: tomcat-embed-el-9.0.54.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'243',
          'label':'bizframe-cloud-server-2.0.85.2.jar: tomcat-embed-websocket-9.0.54.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'244',
          'label':'bizframe-cloud-server-2.0.85.2.jar: xmlbeans-3.1.0.jar'
       },
       {
          'comboId':'com.hundsun.jrescloud',
          'id':'245',
          'label':'bizframe-cloud-server-2.0.85.2.jar: xmlpull-1.1.3.1.jar'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'246',
          'label':'bizframe-cloud-server-2.0.85.2.jar: xstream-1.4.18.jar'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'247',
          'label':'bizframe-cloud-server-2.0.85.2.jar: zookeeper-3.4.14.jar'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'248',
          'label':'bizframe-cloud-server-2.0.85.2.jar: zstd-jni-1.3.8-1.jar'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'249',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ehcache-3.3.1.jar: sizeof-agent.jar'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'250',
          'label':'bizframe-cloud-server-2.0.85.2.jar: common.xml-1.0.3.jar (shaded: com.hundsun.jres.common:com.hundsun.jres.common.xml:1.0.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'251',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curator-client-4.2.0.jar (shaded: com.google.guava:failureaccess:1.0.1)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'252',
          'label':'bizframe-cloud-server-2.0.85.2.jar: curator-client-4.2.0.jar (shaded: com.google.guava:listenablefuture:1.0)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'253',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ehcache-3.3.1.jar (shaded: org.ehcache:sizeof:0.3.0)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'254',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ehcache-3.3.1.jar (shaded: org.terracotta:offheap-store:2.3.2)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'255',
          'label':'bizframe-cloud-server-2.0.85.2.jar: ehcache-3.3.1.jar (shaded: org.terracotta:statistics:1.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'256',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: io.netty:netty-all:4.1.63.Final)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'257',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: com.fasterxml.jackson.core:jackson-databind:2.10.5.1)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'258',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: com.fasterxml.jackson.core:jackson-annotations:2.10.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'259',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: com.fasterxml.jackson.core:jackson-core:2.10.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'260',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: org.latencyutils:LatencyUtils:2.0.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'261',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: org.hdrhistogram:HdrHistogram:2.1.8)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'262',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: org.iq80.snappy:snappy:0.4)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'263',
          'label':'bizframe-cloud-server-2.0.85.2.jar: core-io-1.7.20.jar (shaded: io.opentracing:opentracing-noop:0.31.0)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'264',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-core:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'265',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-aop:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'266',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-bloomFilter:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'267',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-cache:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'268',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-crypto:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'269',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-db:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'270',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-dfa:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'271',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-extra:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'272',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-http:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'273',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-log:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'274',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-script:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'275',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-setting:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'276',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-system:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'277',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-cron:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'278',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-json:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'279',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-poi:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'280',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-captcha:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'281',
          'label':'bizframe-cloud-server-2.0.85.2.jar: hutool-all-5.4.3.jar (shaded: cn.hutool:hutool-socket:5.4.3)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'282',
          'label':'bizframe-cloud-server-2.0.85.2.jar: micrometer-core-1.3.1.jar (shaded: org.pcollections:pcollections:3.1.0)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'283',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-core:1.1.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'284',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-base:1.1.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'285',
          'label':'bizframe-cloud-server-2.0.85.2.jar: oceanbase-client-1.1.7.jar (shaded: com.google.guava:guava:18.0)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'286',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-3.5.6.jar (shaded: ognl:ognl:3.2.15)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'287',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-extra:1.1.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'288',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mybatis-3.5.6.jar (shaded: org.javassist:javassist:3.27.0-GA)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'289',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-spring:1.1.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'290',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-weekend:1.1.5)'
       },
       {
          'comboId':'com.thoughtworks.xstream',
          'id':'291',
          'label':'bizframe-cloud-server-2.0.85.2.jar: mapper-4.1.5.jar (shaded: tk.mybatis:mapper-generator:1.1.5)'
       }
 
    ],
 

      'edges':
      [
         {
            'source':'12',
            'target':'11'
         },
         {
            'source':'12',
            'target':'14'
         },
         {
            'source':'12',
            'target':'16'
         },
         {
            'source':'12',
            'target':'17'
         },
         {
            'source':'13',
            'target':'10'
         },
         {
            'source':'13',
            'target':'14'
         },
         {
            'source':'13',
            'target':'16'
         },
         {
            'source':'13',
            'target':'17'
         },
         {
            'source':'15',
            'target':'8'
         },
         {
            'source':'15',
            'target':'9'
         },
         {
            'source':'15',
            'target':'14'
         },
         {
            'source':'15',
            'target':'16'
         },
         {
            'source':'15',
            'target':'17'
         },
         {
            'source':'15',
            'target':'48'
         },
         {
            'source':'15',
            'target':'134'
         },
         {
            'source':'15',
            'target':'147'
         },
         {
            'source':'15',
            'target':'231'
         },
         {
            'source':'20',
            'target':'10'
         },
         {
            'source':'20',
            'target':'14'
         },
         {
            'source':'20',
            'target':'84'
         },
         {
            'source':'20',
            'target':'246'
         },
         {
            'source':'23',
            'target':'24'
         },
         {
            'source':'23',
            'target':'26'
         },
         {
            'source':'27',
            'target':'32'
         },
         {
            'source':'45',
            'target':'34'
         },
         {
            'source':'45',
            'target':'205'
         },
         {
            'source':'53',
            'target':'22'
         },
         {
            'source':'53',
            'target':'72'
         },
         {
            'source':'53',
            'target':'134'
         },
         {
            'source':'54',
            'target':'69'
         },
         {
            'source':'54',
            'target':'142'
         },
         {
            'source':'54',
            'target':'143'
         },
         {
            'source':'54',
            'target':'145'
         },
         {
            'source':'54',
            'target':'203'
         },
         {
            'source':'54',
            'target':'205'
         },
         {
            'source':'54',
            'target':'288'
         },
         {
            'source':'71',
            'target':'70'
         },
         {
            'source':'119',
            'target':'50'
         },
         {
            'source':'119',
            'target':'51'
         },
         {
            'source':'119',
            'target':'78'
         },
         {
            'source':'119',
            'target':'82'
         },
         {
            'source':'119',
            'target':'285'
         },
         {
            'source':'125',
            'target':'116'
         },
         {
            'source':'125',
            'target':'122'
         },
         {
            'source':'140',
            'target':'31'
         },
         {
            'source':'144',
            'target':'142'
         },
         {
            'source':'144',
            'target':'143'
         },
         {
            'source':'148',
            'target':'149'
         },
         {
            'source':'148',
            'target':'150'
         },
         {
            'source':'148',
            'target':'151'
         },
         {
            'source':'148',
            'target':'152'
         },
         {
            'source':'148',
            'target':'155'
         },
         {
            'source':'148',
            'target':'164'
         },
         {
            'source':'148',
            'target':'165'
         },
         {
            'source':'148',
            'target':'205'
         },
         {
            'source':'148',
            'target':'283'
         },
         {
            'source':'148',
            'target':'284'
         },
         {
            'source':'148',
            'target':'287'
         },
         {
            'source':'148',
            'target':'289'
         },
         {
            'source':'148',
            'target':'290'
         },
         {
            'source':'148',
            'target':'291'
         },
         {
            'source':'169',
            'target':'32'
         },
         {
            'source':'169',
            'target':'49'
         },
         {
            'source':'169',
            'target':'51'
         },
         {
            'source':'169',
            'target':'285'
         },
         {
            'source':'171',
            'target':'30'
         },
         {
            'source':'171',
            'target':'32'
         },
         {
            'source':'171',
            'target':'205'
         },
         {
            'source':'174',
            'target':'51'
         },
         {
            'source':'174',
            'target':'136'
         },
         {
            'source':'174',
            'target':'285'
         },
         {
            'source':'201',
            'target':'70'
         },
         {
            'source':'201',
            'target':'73'
         },
         {
            'source':'201',
            'target':'195'
         },
         {
            'source':'201',
            'target':'202'
         },
         {
            'source':'204',
            'target':'203'
         },
         {
            'source':'11',
            'target':'9'
         },
         {
            'source':'11',
            'target':'120'
         },
         {
            'source':'11',
            'target':'124'
         },
         {
            'source':'16',
            'target':'10'
         },
         {
            'source':'16',
            'target':'14'
         },
         {
            'source':'16',
            'target':'118'
         },
         {
            'source':'16',
            'target':'121'
         },
         {
            'source':'17',
            'target':'10'
         },
         {
            'source':'17',
            'target':'14'
         },
         {
            'source':'17',
            'target':'103'
         },
         {
            'source':'17',
            'target':'118'
         },
         {
            'source':'17',
            'target':'121'
         },
         {
            'source':'48',
            'target':'24'
         },
         {
            'source':'48',
            'target':'31'
         },
         {
            'source':'48',
            'target':'33'
         },
         {
            'source':'134',
            'target':'50'
         },
         {
            'source':'134',
            'target':'136'
         },
         {
            'source':'82',
            'target':'78'
         },
         {
            'source':'82',
            'target':'84'
         },
         {
            'source':'82',
            'target':'96'
         },
         {
            'source':'116',
            'target':'29'
         },
         {
            'source':'116',
            'target':'49'
         },
         {
            'source':'116',
            'target':'111'
         },
         {
            'source':'122',
            'target':'109'
         },
         {
            'source':'202',
            'target':'46'
         },
         {
            'source':'202',
            'target':'70'
         },
         {
            'source':'202',
            'target':'73'
         },
         {
            'source':'202',
            'target':'194'
         },
         {
            'source':'202',
            'target':'195'
         },
         {
            'source':'9',
            'target':'8'
         },
         {
            'source':'10',
            'target':'8'
         },
         {
            'source':'10',
            'target':'120'
         },
         {
            'source':'10',
            'target':'124'
         },
         {
            'source':'14',
            'target':'8'
         },
         {
            'source':'14',
            'target':'57'
         },
         {
            'source':'103',
            'target':'39'
         },
         {
            'source':'103',
            'target':'44'
         },
         {
            'source':'103',
            'target':'100'
         },
         {
            'source':'103',
            'target':'102'
         },
         {
            'source':'103',
            'target':'123'
         },
         {
            'source':'118',
            'target':'84'
         },
         {
            'source':'118',
            'target':'145'
         },
         {
            'source':'121',
            'target':'99'
         },
         {
            'source':'121',
            'target':'107'
         },
         {
            'source':'78',
            'target':'36'
         },
         {
            'source':'78',
            'target':'51'
         },
         {
            'source':'78',
            'target':'77'
         },
         {
            'source':'78',
            'target':'79'
         },
         {
            'source':'78',
            'target':'81'
         },
         {
            'source':'78',
            'target':'83'
         },
         {
            'source':'78',
            'target':'84'
         },
         {
            'source':'78',
            'target':'129'
         },
         {
            'source':'78',
            'target':'285'
         },
         {
            'source':'29',
            'target':'30'
         },
         {
            'source':'109',
            'target':'39'
         },
         {
            'source':'109',
            'target':'84'
         },
         {
            'source':'109',
            'target':'87'
         },
         {
            'source':'109',
            'target':'108'
         },
         {
            'source':'120',
            'target':'84'
         },
         {
            'source':'8',
            'target':'132'
         },
         {
            'source':'8',
            'target':'246'
         },
         {
            'source':'57',
            'target':'33'
         },
         {
            'source':'57',
            'target':'43'
         },
         {
            'source':'57',
            'target':'70'
         },
         {
            'source':'57',
            'target':'72'
         },
         {
            'source':'57',
            'target':'74'
         },
         {
            'source':'57',
            'target':'143'
         },
         {
            'source':'57',
            'target':'205'
         },
         {
            'source':'57',
            'target':'264'
         },
         {
            'source':'57',
            'target':'265'
         },
         {
            'source':'57',
            'target':'266'
         },
         {
            'source':'57',
            'target':'267'
         },
         {
            'source':'57',
            'target':'268'
         },
         {
            'source':'57',
            'target':'269'
         },
         {
            'source':'57',
            'target':'270'
         },
         {
            'source':'57',
            'target':'271'
         },
         {
            'source':'57',
            'target':'272'
         },
         {
            'source':'57',
            'target':'273'
         },
         {
            'source':'57',
            'target':'274'
         },
         {
            'source':'57',
            'target':'275'
         },
         {
            'source':'57',
            'target':'276'
         },
         {
            'source':'57',
            'target':'277'
         },
         {
            'source':'57',
            'target':'278'
         },
         {
            'source':'57',
            'target':'279'
         },
         {
            'source':'57',
            'target':'280'
         },
         {
            'source':'57',
            'target':'281'
         },
         {
            'source':'44',
            'target':'43'
         },
         {
            'source':'44',
            'target':'70'
         },
         {
            'source':'44',
            'target':'205'
         },
         {
            'source':'123',
            'target':'93'
         },
         {
            'source':'123',
            'target':'94'
         },
         {
            'source':'123',
            'target':'154'
         },
         {
            'source':'123',
            'target':'181'
         },
         {
            'source':'107',
            'target':'105'
         },
         {
            'source':'107',
            'target':'106'
         },
         {
            'source':'79',
            'target':'67'
         },
         {
            'source':'79',
            'target':'77'
         },
         {
            'source':'79',
            'target':'84'
         },
         {
            'source':'81',
            'target':'77'
         },
         {
            'source':'81',
            'target':'85'
         },
         {
            'source':'81',
            'target':'240'
         },
         {
            'source':'83',
            'target':'77'
         },
         {
            'source':'83',
            'target':'80'
         },
         {
            'source':'83',
            'target':'84'
         },
         {
            'source':'83',
            'target':'231'
         },
         {
            'source':'87',
            'target':'69'
         },
         {
            'source':'87',
            'target':'205'
         },
         {
            'source':'87',
            'target':'288'
         },
         {
            'source':'108',
            'target':'32'
         },
         {
            'source':'108',
            'target':'84'
         },
         {
            'source':'132',
            'target':'25'
         },
         {
            'source':'132',
            'target':'32'
         },
         {
            'source':'132',
            'target':'49'
         },
         {
            'source':'132',
            'target':'131'
         },
         {
            'source':'132',
            'target':'205'
         },
         {
            'source':'93',
            'target':'92'
         },
         {
            'source':'94',
            'target':'92'
         },
         {
            'source':'94',
            'target':'96'
         },
         {
            'source':'154',
            'target':'149'
         },
         {
            'source':'154',
            'target':'150'
         },
         {
            'source':'154',
            'target':'151'
         },
         {
            'source':'154',
            'target':'152'
         },
         {
            'source':'154',
            'target':'153'
         },
         {
            'source':'154',
            'target':'155'
         },
         {
            'source':'154',
            'target':'164'
         },
         {
            'source':'154',
            'target':'165'
         },
         {
            'source':'154',
            'target':'283'
         },
         {
            'source':'154',
            'target':'284'
         },
         {
            'source':'154',
            'target':'287'
         },
         {
            'source':'154',
            'target':'289'
         },
         {
            'source':'154',
            'target':'290'
         },
         {
            'source':'181',
            'target':'167'
         },
         {
            'source':'181',
            'target':'179'
         },
         {
            'source':'181',
            'target':'180'
         },
         {
            'source':'105',
            'target':'104'
         },
         {
            'source':'106',
            'target':'104'
         },
         {
            'source':'67',
            'target':'33'
         },
         {
            'source':'67',
            'target':'36'
         },
         {
            'source':'67',
            'target':'205'
         },
         {
            'source':'240',
            'target':'143'
         },
         {
            'source':'240',
            'target':'145'
         },
         {
            'source':'77',
            'target':'49'
         },
         {
            'source':'77',
            'target':'80'
         },
         {
            'source':'77',
            'target':'84'
         },
         {
            'source':'77',
            'target':'129'
         },
         {
            'source':'77',
            'target':'161'
         },
         {
            'source':'77',
            'target':'231'
         },
         {
            'source':'92',
            'target':'43'
         },
         {
            'source':'92',
            'target':'91'
         },
         {
            'source':'151',
            'target':'149'
         },
         {
            'source':'151',
            'target':'150'
         },
         {
            'source':'151',
            'target':'164'
         },
         {
            'source':'151',
            'target':'283'
         },
         {
            'source':'151',
            'target':'284'
         },
         {
            'source':'153',
            'target':'150'
         },
         {
            'source':'153',
            'target':'152'
         },
         {
            'source':'153',
            'target':'164'
         },
         {
            'source':'153',
            'target':'165'
         },
         {
            'source':'153',
            'target':'205'
         },
         {
            'source':'153',
            'target':'283'
         },
         {
            'source':'153',
            'target':'289'
         },
         {
            'source':'155',
            'target':'149'
         },
         {
            'source':'155',
            'target':'150'
         },
         {
            'source':'155',
            'target':'164'
         },
         {
            'source':'155',
            'target':'283'
         },
         {
            'source':'155',
            'target':'284'
         },
         {
            'source':'167',
            'target':'164'
         },
         {
            'source':'167',
            'target':'165'
         },
         {
            'source':'167',
            'target':'166'
         },
         {
            'source':'180',
            'target':'164'
         },
         {
            'source':'180',
            'target':'166'
         },
         {
            'source':'180',
            'target':'179'
         },
         {
            'source':'104',
            'target':'99'
         },
         {
            'source':'36',
            'target':'2'
         },
         {
            'source':'36',
            'target':'33'
         },
         {
            'source':'36',
            'target':'51'
         },
         {
            'source':'36',
            'target':'52'
         },
         {
            'source':'36',
            'target':'59'
         },
         {
            'source':'36',
            'target':'60'
         },
         {
            'source':'36',
            'target':'61'
         },
         {
            'source':'36',
            'target':'141'
         },
         {
            'source':'36',
            'target':'176'
         },
         {
            'source':'36',
            'target':'177'
         },
         {
            'source':'36',
            'target':'186'
         },
         {
            'source':'36',
            'target':'205'
         },
         {
            'source':'36',
            'target':'256'
         },
         {
            'source':'36',
            'target':'257'
         },
         {
            'source':'36',
            'target':'258'
         },
         {
            'source':'36',
            'target':'259'
         },
         {
            'source':'36',
            'target':'260'
         },
         {
            'source':'36',
            'target':'261'
         },
         {
            'source':'36',
            'target':'262'
         },
         {
            'source':'36',
            'target':'263'
         },
         {
            'source':'36',
            'target':'285'
         },
         {
            'source':'80',
            'target':'35'
         },
         {
            'source':'80',
            'target':'74'
         },
         {
            'source':'80',
            'target':'205'
         },
         {
            'source':'80',
            'target':'231'
         },
         {
            'source':'43',
            'target':'33'
         },
         {
            'source':'43',
            'target':'49'
         },
         {
            'source':'43',
            'target':'51'
         },
         {
            'source':'43',
            'target':'70'
         },
         {
            'source':'43',
            'target':'142'
         },
         {
            'source':'43',
            'target':'143'
         },
         {
            'source':'43',
            'target':'164'
         },
         {
            'source':'43',
            'target':'165'
         },
         {
            'source':'43',
            'target':'205'
         },
         {
            'source':'43',
            'target':'285'
         },
         {
            'source':'91',
            'target':'84'
         },
         {
            'source':'152',
            'target':'149'
         },
         {
            'source':'152',
            'target':'150'
         },
         {
            'source':'152',
            'target':'164'
         },
         {
            'source':'152',
            'target':'165'
         },
         {
            'source':'152',
            'target':'205'
         },
         {
            'source':'152',
            'target':'283'
         },
         {
            'source':'152',
            'target':'284'
         },
         {
            'source':'166',
            'target':'164'
         },
         {
            'source':'166',
            'target':'165'
         },
         {
            'source':'166',
            'target':'205'
         },
         {
            'source':'179',
            'target':'51'
         },
         {
            'source':'179',
            'target':'135'
         },
         {
            'source':'179',
            'target':'164'
         },
         {
            'source':'179',
            'target':'285'
         },
         {
            'source':'99',
            'target':'98'
         },
         {
            'source':'141',
            'target':'52'
         },
         {
            'source':'141',
            'target':'261'
         },
         {
            'source':'165',
            'target':'164'
         },
         {
            'source':'165',
            'target':'286'
         },
         {
            'source':'135',
            'target':'30'
         },
         {
            'source':'98',
            'target':'1'
         },
         {
            'source':'98',
            'target':'35'
         },
         {
            'source':'98',
            'target':'55'
         },
         {
            'source':'98',
            'target':'100'
         },
         {
            'source':'98',
            'target':'102'
         },
         {
            'source':'98',
            'target':'161'
         },
         {
            'source':'1',
            'target':'61'
         },
         {
            'source':'1',
            'target':'205'
         },
         {
            'source':'1',
            'target':'257'
         },
         {
            'source':'102',
            'target':'69'
         },
         {
            'source':'102',
            'target':'100'
         },
         {
            'source':'102',
            'target':'124'
         },
         {
            'source':'102',
            'target':'288'
         },
         {
            'source':'161',
            'target':'50'
         },
         {
            'source':'161',
            'target':'160'
         },
         {
            'source':'100',
            'target':'97'
         },
         {
            'source':'100',
            'target':'101'
         },
         {
            'source':'100',
            'target':'159'
         },
         {
            'source':'100',
            'target':'205'
         },
         {
            'source':'124',
            'target':'112'
         },
         {
            'source':'124',
            'target':'113'
         },
         {
            'source':'124',
            'target':'114'
         },
         {
            'source':'124',
            'target':'115'
         },
         {
            'source':'101',
            'target':'61'
         },
         {
            'source':'101',
            'target':'97'
         },
         {
            'source':'101',
            'target':'159'
         },
         {
            'source':'101',
            'target':'205'
         },
         {
            'source':'101',
            'target':'257'
         },
         {
            'source':'113',
            'target':'112'
         },
         {
            'source':'114',
            'target':'96'
         },
         {
            'source':'114',
            'target':'110'
         },
         {
            'source':'114',
            'target':'112'
         },
         {
            'source':'115',
            'target':'89'
         },
         {
            'source':'115',
            'target':'112'
         },
         {
            'source':'97',
            'target':'90'
         },
         {
            'source':'97',
            'target':'127'
         },
         {
            'source':'159',
            'target':'59'
         },
         {
            'source':'159',
            'target':'61'
         },
         {
            'source':'159',
            'target':'158'
         },
         {
            'source':'159',
            'target':'257'
         },
         {
            'source':'159',
            'target':'258'
         },
         {
            'source':'96',
            'target':'95'
         },
         {
            'source':'96',
            'target':'110'
         },
         {
            'source':'112',
            'target':'38'
         },
         {
            'source':'112',
            'target':'39'
         },
         {
            'source':'112',
            'target':'49'
         },
         {
            'source':'112',
            'target':'55'
         },
         {
            'source':'112',
            'target':'56'
         },
         {
            'source':'112',
            'target':'69'
         },
         {
            'source':'112',
            'target':'89'
         },
         {
            'source':'112',
            'target':'117'
         },
         {
            'source':'112',
            'target':'127'
         },
         {
            'source':'112',
            'target':'129'
         },
         {
            'source':'112',
            'target':'130'
         },
         {
            'source':'112',
            'target':'170'
         },
         {
            'source':'112',
            'target':'172'
         },
         {
            'source':'112',
            'target':'206'
         },
         {
            'source':'112',
            'target':'288'
         },
         {
            'source':'158',
            'target':'24'
         },
         {
            'source':'158',
            'target':'32'
         },
         {
            'source':'158',
            'target':'51'
         },
         {
            'source':'158',
            'target':'61'
         },
         {
            'source':'158',
            'target':'205'
         },
         {
            'source':'158',
            'target':'257'
         },
         {
            'source':'158',
            'target':'285'
         },
         {
            'source':'95',
            'target':'84'
         },
         {
            'source':'110',
            'target':'84'
         },
         {
            'source':'55',
            'target':'25'
         },
         {
            'source':'55',
            'target':'33'
         },
         {
            'source':'55',
            'target':'56'
         },
         {
            'source':'89',
            'target':'38'
         },
         {
            'source':'89',
            'target':'39'
         },
         {
            'source':'89',
            'target':'49'
         },
         {
            'source':'89',
            'target':'170'
         },
         {
            'source':'89',
            'target':'205'
         },
         {
            'source':'117',
            'target':'24'
         },
         {
            'source':'117',
            'target':'25'
         },
         {
            'source':'117',
            'target':'90'
         },
         {
            'source':'117',
            'target':'111'
         },
         {
            'source':'127',
            'target':'126'
         },
         {
            'source':'129',
            'target':'128'
         },
         {
            'source':'129',
            'target':'143'
         },
         {
            'source':'130',
            'target':'128'
         },
         {
            'source':'130',
            'target':'186'
         },
         {
            'source':'130',
            'target':'187'
         },
         {
            'source':'172',
            'target':'33'
         },
         {
            'source':'172',
            'target':'72'
         },
         {
            'source':'172',
            'target':'186'
         },
         {
            'source':'172',
            'target':'205'
         },
         {
            'source':'206',
            'target':'30'
         },
         {
            'source':'206',
            'target':'32'
         },
         {
            'source':'56',
            'target':'33'
         },
         {
            'source':'39',
            'target':'38'
         },
         {
            'source':'170',
            'target':'25'
         },
         {
            'source':'170',
            'target':'51'
         },
         {
            'source':'170',
            'target':'60'
         },
         {
            'source':'170',
            'target':'61'
         },
         {
            'source':'170',
            'target':'143'
         },
         {
            'source':'170',
            'target':'145'
         },
         {
            'source':'170',
            'target':'203'
         },
         {
            'source':'170',
            'target':'205'
         },
         {
            'source':'170',
            'target':'257'
         },
         {
            'source':'170',
            'target':'259'
         },
         {
            'source':'170',
            'target':'285'
         },
         {
            'source':'111',
            'target':'84'
         },
         {
            'source':'111',
            'target':'90'
         },
         {
            'source':'126',
            'target':'3'
         },
         {
            'source':'126',
            'target':'4'
         },
         {
            'source':'126',
            'target':'84'
         },
         {
            'source':'126',
            'target':'128'
         },
         {
            'source':'187',
            'target':'47'
         },
         {
            'source':'187',
            'target':'50'
         },
         {
            'source':'187',
            'target':'51'
         },
         {
            'source':'187',
            'target':'285'
         },
         {
            'source':'72',
            'target':'142'
         },
         {
            'source':'72',
            'target':'205'
         },
         {
            'source':'186',
            'target':'51'
         },
         {
            'source':'186',
            'target':'285'
         },
         {
            'source':'3',
            'target':'176'
         },
         {
            'source':'3',
            'target':'177'
         },
         {
            'source':'3',
            'target':'263'
         },
         {
            'source':'128',
            'target':'84'
         },
         {
            'source':'128',
            'target':'90'
         },
         {
            'source':'84',
            'target':'70'
         },
         {
            'source':'84',
            'target':'73'
         },
         {
            'source':'84',
            'target':'85'
         },
         {
            'source':'84',
            'target':'138'
         },
         {
            'source':'84',
            'target':'216'
         },
         {
            'source':'90',
            'target':'24'
         },
         {
            'source':'90',
            'target':'85'
         },
         {
            'source':'138',
            'target':'205'
         },
         {
            'source':'216',
            'target':'70'
         },
         {
            'source':'85',
            'target':'49'
         },
         {
            'source':'85',
            'target':'61'
         },
         {
            'source':'85',
            'target':'63'
         },
         {
            'source':'85',
            'target':'86'
         },
         {
            'source':'85',
            'target':'257'
         },
         {
            'source':'49',
            'target':'70'
         },
         {
            'source':'49',
            'target':'231'
         },
         {
            'source':'86',
            'target':'88'
         },
         {
            'source':'86',
            'target':'205'
         },
         {
            'source':'231',
            'target':'24'
         },
         {
            'source':'231',
            'target':'35'
         },
         {
            'source':'231',
            'target':'60'
         },
         {
            'source':'231',
            'target':'61'
         },
         {
            'source':'231',
            'target':'63'
         },
         {
            'source':'231',
            'target':'74'
         },
         {
            'source':'231',
            'target':'230'
         },
         {
            'source':'231',
            'target':'246'
         },
         {
            'source':'231',
            'target':'257'
         },
         {
            'source':'231',
            'target':'259'
         },
         {
            'source':'88',
            'target':'205'
         },
         {
            'source':'63',
            'target':'59'
         },
         {
            'source':'63',
            'target':'258'
         },
         {
            'source':'74',
            'target':'35'
         },
         {
            'source':'74',
            'target':'143'
         },
         {
            'source':'74',
            'target':'145'
         },
         {
            'source':'74',
            'target':'205'
         },
         {
            'source':'230',
            'target':'229'
         },
         {
            'source':'246',
            'target':'31'
         },
         {
            'source':'246',
            'target':'163'
         },
         {
            'source':'145',
            'target':'32'
         },
         {
            'source':'145',
            'target':'142'
         },
         {
            'source':'145',
            'target':'143'
         },
         {
            'source':'145',
            'target':'205'
         },
         {
            'source':'229',
            'target':'51'
         },
         {
            'source':'229',
            'target':'61'
         },
         {
            'source':'229',
            'target':'70'
         },
         {
            'source':'229',
            'target':'257'
         },
         {
            'source':'229',
            'target':'285'
         }
   
      ],
   
'combos':
        [
           {
              
           },
           {
              'label':'com.rabbitmq',
              'id':'com.rabbitmq'
           },
           {
              'label':'org.codehaus.mojo',
              'id':'org.codehaus.mojo'
           },
           {
              'label':'org.apache.skywalking',
              'id':'org.apache.skywalking'
           },
           {
              'label':'org.apache.yetus',
              'id':'org.apache.yetus'
           },
           {
              'label':'com.hundsun.jres.bizframe2',
              'id':'com.hundsun.jres.bizframe2'
           },
           {
              'label':'com.fasterxml',
              'id':'com.fasterxml'
           },
           {
              'label':'com.hundsun.jres.common',
              'id':'com.hundsun.jres.common'
           },
           {
              'label':'commons-beanutils',
              'id':'commons-beanutils'
           },
           {
              'label':'commons-codec',
              'id':'commons-codec'
           },
           {
              'label':'commons-collections',
              'id':'commons-collections'
           },
           {
              'label':'org.apache.commons',
              'id':'org.apache.commons'
           },
           {
              'label':'commons-fileupload',
              'id':'commons-fileupload'
           },
           {
              'label':'commons-io',
              'id':'commons-io'
           },
           {
              'label':'commons-lang',
              'id':'commons-lang'
           },
           {
              'label':'commons-logging',
              'id':'commons-logging'
           },
           {
              'label':'io.opentracing',
              'id':'io.opentracing'
           },
           {
              'label':'com.google.guava',
              'id':'com.google.guava'
           },
           {
              'label':'org.apache.curator',
              'id':'org.apache.curator'
           },
           {
              'label':'com.github.virtuald',
              'id':'com.github.virtuald'
           },
           {
              'label':'com.alibaba',
              'id':'com.alibaba'
           },
           {
              'label':'org.terracotta',
              'id':'org.terracotta'
           },
           {
              'label':'org.owasp.encoder',
              'id':'org.owasp.encoder'
           },
           {
              'label':'com.google.errorprone',
              'id':'com.google.errorprone'
           },
           {
              'label':'net.sf.ezmorph',
              'id':'net.sf.ezmorph'
           },
           {
              'label':'com.google.code.gson',
              'id':'com.google.code.gson'
           },
           {
              'label':'org.hdrhistogram',
              'id':'org.hdrhistogram'
           },
           {
              'label':'org.hibernate.validator',
              'id':'org.hibernate.validator'
           },
           {
              'label':'com.zaxxer',
              'id':'com.zaxxer'
           },
           {
              'label':'org.apache.httpcomponents',
              'id':'org.apache.httpcomponents'
           },
           {
              'label':'cn.hutool',
              'id':'cn.hutool'
           },
           {
              'label':'com.google.j2objc',
              'id':'com.google.j2objc'
           },
           {
              'label':'com.fasterxml.jackson.core',
              'id':'com.fasterxml.jackson.core'
           },
           {
              'label':'com.fasterxml.jackson.datatype',
              'id':'com.fasterxml.jackson.datatype'
           },
           {
              'label':'com.fasterxml.jackson.module',
              'id':'com.fasterxml.jackson.module'
           },
           {
              'label':'jakarta.annotation',
              'id':'jakarta.annotation'
           },
           {
              'label':'jakarta.validation',
              'id':'jakarta.validation'
           },
           {
              'label':'com.couchbase.client',
              'id':'com.couchbase.client'
           },
           {
              'label':'org.javassist',
              'id':'org.javassist'
           },
           {
              'label':'javax.servlet',
              'id':'javax.servlet'
           },
           {
              'label':'javax.servlet.jsp',
              'id':'javax.servlet.jsp'
           },
           {
              'label':'org.jboss.logging',
              'id':'org.jboss.logging'
           },
           {
              'label':'org.slf4j',
              'id':'org.slf4j'
           },
           {
              'label':'redis.clients',
              'id':'redis.clients'
           },
           {
              'label':'jline',
              'id':'jline'
           },
           {
              'label':'com.hundsun.jrescloud',
              'id':'com.hundsun.jrescloud'
           },
           {
              'label':'com.hundsun.jresplus',
              'id':'com.hundsun.jresplus'
           },
           {
              'label':'org.jsoup',
              'id':'org.jsoup'
           },
           {
              'label':'com.github.jsqlparser',
              'id':'com.github.jsqlparser'
           },
           {
              'label':'com.google.code.findbugs',
              'id':'com.google.code.findbugs'
           },
           {
              'label':'com.esotericsoftware',
              'id':'com.esotericsoftware'
           },
           {
              'label':'org.latencyutils',
              'id':'org.latencyutils'
           },
           {
              'label':'org.apache.logging.log4j',
              'id':'org.apache.logging.log4j'
           },
           {
              'label':'javax.mail',
              'id':'javax.mail'
           },
           {
              'label':'tk.mybatis',
              'id':'tk.mybatis'
           },
           {
              'label':'org.pcollections',
              'id':'org.pcollections'
           },
           {
              'label':'com.hundsun.jrescloud.middleware',
              'id':'com.hundsun.jrescloud.middleware'
           },
           {
              'label':'io.github.x-stream',
              'id':'io.github.x-stream'
           },
           {
              'label':'org.mybatis',
              'id':'org.mybatis'
           },
           {
              'label':'org.mybatis.spring.boot',
              'id':'org.mybatis.spring.boot'
           },
           {
              'label':'com.alibaba.nacos',
              'id':'com.alibaba.nacos'
           },
           {
              'label':'io.netty',
              'id':'io.netty'
           },
           {
              'label':'com.github.pagehelper',
              'id':'com.github.pagehelper'
           },
           {
              'label':'com.google.protobuf',
              'id':'com.google.protobuf'
           },
           {
              'label':'org.apache.shiro',
              'id':'org.apache.shiro'
           },
           {
              'label':'io.prometheus',
              'id':'io.prometheus'
           },
           {
              'label':'org.yaml',
              'id':'org.yaml'
           },
           {
              'label':'org.springframework.boot',
              'id':'org.springframework.boot'
           },
           {
              'label':'org.springframework.data',
              'id':'org.springframework.data'
           },
           {
              'label':'com.thoughtworks.xstream',
              'id':'com.thoughtworks.xstream'
           }
     
        ]

  
};

data.nodes.forEach((node) => {
  switch (node.ComboId) {
    default:
      node.style = {
        fill: "#FDE1CE",
        stroke: "#aaa"
      };
      break;
  }
});

let sortByCombo = false;
const descriptionDiv = document.createElement("button");
descriptionDiv.innerHTML = "Enable sortByCombo";
const container = document.getElementById("container");
container.appendChild(descriptionDiv);

descriptionDiv.addEventListener("click", (e) => {
  sortByCombo = !sortByCombo;
  descriptionDiv.innerHTML = sortByCombo
    ? "Disable sortByCombo"
    : "Enable sortByCombo";
  graph.updateLayout({
    sortByCombo
  });
});
const width = container.scrollWidth;
const height = (container.scrollHeight || 500) - 30;
const graph = new G6.Graph({
  container: "container",
  width: width + 100,
  height: height + 1000,
  // fitView: true,
  fitViewPadding: 30,
  animate: true,
  groupByTypes: false,
  modes: {
    default: [
      "drag-combo",
      "drag-node",
      "drag-canvas",
      {
        type: "collapse-expand-combo",
        relayout: false
      }
    ]
  },
  layout: {
    type: "dagre",
    sortByCombo: false,
    ranksep: 10,
    nodesep: 10
  },
  defaultNode: {
    size: [500, 100],
    type: "rect",
    anchorPoints: [
      [0.5, 0],
      [0.5, 1]
    ]
  },
  defaultEdge: {
    type: "line"
  },
  defaultCombo: {
    type: "rect",
    
    style: {
      fillOpacity: 0.1
    }
  }
});
graph.data(data);
graph.render();

console.log("comboTrees", graph.get("comboTrees"));

if (typeof window !== "undefined")
  window.onresize = () => {
    if (!graph || graph.get("destroyed")) return;
    if (!container || !container.scrollWidth || !container.scrollHeight) return;
    graph.changeSize(container.scrollWidth, container.scrollHeight - 30);
  };

